class AppAssets {
  static const iconpath = "assets/icon/";
  static const lottiepath = "assets/lottie/";
  static const imagepath = "assets/image/";

  static const String onbording = "${imagepath}onbording.png";

  static const String layar1 = "${imagepath}layar1.png";
  static const String layer2 = "${imagepath}layer2.png";
  static const String layer3 = "${imagepath}layer3.png";
  static const String arrowleft = "${iconpath}arrowleft.svg";
  static const String facebooksvg = "${iconpath}facebooksvg.svg";
  static const String twittersvg = "${iconpath}twittersvg.svg";
  static const String googlesvg = "${iconpath}googlesvg.svg";
  static const String forgetpassword = "${imagepath}forgetpassword.png";
  static const String homesvg = "${iconpath}Homesvg.svg";
  static const String heartsvg = "${iconpath}Heartsvg.svg";
  static const String bagsvg = "${iconpath}Bagsvg.svg";
  static const String walletsvg = "${iconpath}Walletsvg.svg";
  static const String menusvg = "${iconpath}menusvg.svg";
  static const String searchsvg = "${iconpath}searchsvg.svg";
  static const String voicesvg = "${iconpath}voicesvg.svg";
  static const String starsvg = "${iconpath}starsvg.svg";
  static const String editsvg = "${iconpath}editsvg.svg";
  static const String profile = "${iconpath}profile.svg";
  static const String clocksvg = "${iconpath}clocksvg.svg";
  static const String delete = "${iconpath}delete.svg";
  static const String arrowup = "${iconpath}arrowup.svg";
  static const String arrowdown = "${iconpath}arrowdown.svg";
  static const String arrowright = "${iconpath}arrowright.svg";
  static const String locationsvg = "${iconpath}locationsvg.svg";
  static const String mapimage = "${imagepath}mapimage.png";
  static const String checksvg = "${iconpath}checksvg.svg";
  static const String vicaimage = "${imagepath}vicaimage.png";
  static const String vector1 = "${imagepath}Vector1.png";
  static const String vector2 = "${imagepath}vector2.png";
  static const String vector3 = "${imagepath}vector3.png";
  // static const String checksvg6 = "${iconpath}checksvg6.svg";
  // static const String checksvg7 = "${iconpath}checksvg7.svg";
  // static const String checksvg8 = "${iconpath}checksvg8.svg";
  // static const String checksvg9 = "${iconpath}checksvg9.svg";
  // static const String checksvg10 = "${iconpath}checksvg10.svg";
  // static const String checksvg11 = "${iconpath}checksvg11.svg";
  // static const String checksvg12 = "${iconpath}checksvg12.svg";
  // static const String checksvg13 = "${iconpath}checksvg13.svg";
  // static const String checksvg14 = "${iconpath}checksvg14.svg";
  // static const String checksvg15 = "${iconpath}checksvg15.svg";
  // static const String checksvg16 = "${iconpath}checksvg16.svg";
}
